services:
  db:
    image: postgres:16.6
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=e-commerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1214212530
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data: